.PHONY: clean All

All:
	@echo "----------Building project:[ ex3remdupl - macOS ]----------"
	@cd "ex3remdupl" && "$(MAKE)" -f  "ex3remdupl.mk"
clean:
	@echo "----------Cleaning project:[ ex3remdupl - macOS ]----------"
	@cd "ex3remdupl" && "$(MAKE)" -f  "ex3remdupl.mk" clean
