.PHONY: clean All

All:
	@echo "----------Building project:[ ex10aldern - macOS ]----------"
	@cd "ex10aldern" && "$(MAKE)" -f  "ex10aldern.mk"
clean:
	@echo "----------Cleaning project:[ ex10aldern - macOS ]----------"
	@cd "ex10aldern" && "$(MAKE)" -f  "ex10aldern.mk" clean
