.PHONY: clean All

All:
	@echo "----------Building project:[ caesar - macOS ]----------"
	@cd "caesar" && "$(MAKE)" -f  "caesar.mk"
clean:
	@echo "----------Cleaning project:[ caesar - macOS ]----------"
	@cd "caesar" && "$(MAKE)" -f  "caesar.mk" clean
