.PHONY: clean All

All:
	@echo "----------Building project:[ ex9skalarproduct - macOS ]----------"
	@cd "ex9skalarproduct" && "$(MAKE)" -f  "ex9skalarproduct.mk"
clean:
	@echo "----------Cleaning project:[ ex9skalarproduct - macOS ]----------"
	@cd "ex9skalarproduct" && "$(MAKE)" -f  "ex9skalarproduct.mk" clean
