.PHONY: clean All

All:
	@echo "----------Building project:[ ex5day_nbr - macOS ]----------"
	@cd "ex5day_nbr" && "$(MAKE)" -f  "ex5day_nbr.mk"
clean:
	@echo "----------Cleaning project:[ ex5day_nbr - macOS ]----------"
	@cd "ex5day_nbr" && "$(MAKE)" -f  "ex5day_nbr.mk" clean
